### ISSUE TITLE
Cannot make vcn authenticate on cnlcdocs

### ISSUE THREAD

**Issue by Giako** [vchain-us/vcn#116]
With the latest `vcn` master, on LC, when trying to authenticate an asset notarized on the internal ledger, this is the outcome (the example is verifying an audit report):

```
$ ./vcn a ledger_29666890513461348__12_08_2020-13_00__12_09_2020-13_00.pdf --lc-port 33080 --lc-host ppp.immudb.io

Warning: rpc error: code = Unknown desc = Time.UnmarshalBinary: unsupported version
```

Adding @amangale too for verification on what the BE is writing.

**Comment by mmeloni** [comment]
It's not related to vcn, it's lc that is using an old and never released version.
Fixed in https://github.com/vchain-us/ledger-compliance/pull/422
