### ISSUE TITLE
Enhancement to vcn "usage"

### ISSUE THREAD

**Issue by ivan-w** [vchain-us/vcn#59]
The vcn default help may probably need to list all the supported schemes/extractors supported and maybe their syntax.. Something like : 
```
ARG should be one of : 
[file://]<file> (the default)
git://<git repository>
docker://<docker image>
dir://<directory>
podman://<you tell me>
```

**Comment by ivan-w** [comment]
(I guess it should be possible to run through the extractors and ask them...)

**Comment by leogr** [comment]
Partially done on 0.7.0.
Unfortunately, extractors do not have enough info to build the help message automatically, so I did it manually.
