### ISSUE TITLE
not found when trying to run vcn command on docker image

### ISSUE THREAD

**Issue by dzlabsch** [vchain-us/vcn#74]
**What happened**
I downloaded vcn when running the docker:latest based container:
```shell
curl -L -o /tmp/vcn https://github.com/vchain-us/vcn/releases/download/v0.7.3/vcn-v0.7.3-linux-amd64
chmod +x /tmp/vcn
```
When running /tmp/vcn I get an error:
```shell
sh: /tmp/vcn: not found
```

**What you expected to happen**
That vcn command works

**How to reproduce it (as minimally and precisely as possible)**
```shell
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock docker:19.03.1
apk add --no-cache curl
curl -L -o /tmp/vcn https://github.com/vchain-us/vcn/releases/download/v0.7.3/vcn-v0.7.3-linux-amd64
chmod +x /tmp/vcn
/tmp/vcn help
```

**Additional info**
when running ldd I get 
```shell
/ # ldd /tmp/vcn
        /lib64/ld-linux-x86-64.so.2 (0x7f6ce3fc4000)
        libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f6ce3fc4000)
        libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f6ce3fc4000)
Error relocating /tmp/vcn: __fprintf_chk: symbol not found
```

**Comment by leogr** [comment]
Hi @dzlabsch 

I've uploaded the statically linked build that should fix this issue:
https://github.com/vchain-us/vcn/releases/tag/v0.7.3

Let me know if it works! Thanks.

**Comment by dzlabsch** [comment]
Works! Thanks a lot for the quick turnaround
