### ISSUE TITLE
silent parameter for authenticate similar to docker-compose

### ISSUE THREAD

**Issue by dzlabsch** [vchain-us/vcn#75]
**What would you like to be added or enhanced**
Currently all information is shown when authenticating a object, i. e. a docker image.
I would like to have a quiet switch like docker-compose so only the trust level is shown.

**Why is this needed**
When scripting sometimes only the most important info is of interest.
Example docker-compose images shows
```
   Container      Repository    Tag       Image Id      Size
--------------------------------------------------------------
gitlab            <none>       <none>   0e39d6e67b26   1.67 GB

```
while docker-compose images -q shows:
`0e39d6e67b264fd3c4c110d8c971799941e6f97e799240843ba67f504fce8b88`

Much better to work with.

It would be great if vcn auth -q would only show something like:
UNKNOWN
or TRUSTED

instead of all information.

**Comment by leogr** [comment]
Unfortunately, the `-q` shorthand is already [taken](https://github.com/vchain-us/vcn/blob/master/pkg/cmd/cmd.go#L88).
But I like this idea, so we'll find an alternative naming for that :)

**Comment by leogr** [comment]
The `--silent` flag was introduced since [v0.7.4](https://github.com/vchain-us/vcn/blob/master/CHANGELOG.md#features)
