### ISSUE TITLE
tool section reacting weird

### ISSUE THREAD

**Issue by moshix** [vchain-us/vcn#83]
I go to the tools section in the dashboard:

1. No link to the github where I can download it from because if I want to install it on a remote server, I cannot download it from the dashboard, I need a wget link.... (we have said this many, many times, needs fixing now)

2. it starts to download from the CLI tools section, but the clock keeeps spinning, and if I then go back to the main page and return to the CLI tool section I never get the presented the choice of CLI tools by OS (Mac Linux or Windoze). 

thanks

M

**Comment by peet86** [comment]
1.  We have a solution called getvcn which is a small "online" install script. We call it "Install" on the Dashboard (tools section) and it's available for both linux and mac. 
It uses curl in the background to download the latest binary + does all the installation steps you need on a *nix system. I think this is the best solution for end users. 

I've added a "wget link" option too for users who only want to download it from the cli.

2. Now it's possible to download vcn even when a previous vcn onboarding is in progress.
