### ISSUE TITLE
Notarize from a script

### ISSUE THREAD

**Issue by moshix** [vchain-us/vcn#86]
How can I have vcn notarize from a script, so I am not asked for the password each time?

thanks

M

**Comment by dzlabsch** [comment]
You can use a the environment variables (https://docs.codenotary.io/vcn/user-guide/environments.html#other-environment-variables):

```
VCN_NOTARIZATION_PASSWORD
```
like
VCN_NOTARIZATION_PASSWORD="pw" vcn n ...

or load it into the environment of the system or container that runs vcn

**Comment by moshix** [comment]
Doesn’t work for me:

#!/bin/bash

VCN_USER=moshe@vchain.us
VCN_PASSWORD=soso
VCN_NOTARIZATION_PASSWORD=soso
vcn login
for ((i=1;i<=100;i++));
do
/bin/vcn n dir://adv.labs
   echo $i
done

**Comment by dzlabsch** [comment]
in a bash script try

```
#!/bin/bash

export VCN_USER=moshe@vchain.us
exxport VCN_PASSWORD=soso
export VCN_NOTARIZATION_PASSWORD=soso
vcn login
for ((i=1;i<=100;i++));
do
/bin/vcn n dir://adv.labs
   echo $i
done
```
