### ISSUE TITLE
Parallel notarization impossible 

### ISSUE THREAD

**Issue by jkornata** [vchain-us/vcn#95]
**What happened**
While running a parallel job in Jenkins only one of a few parallel branches ended up with a success. Job was supposed to sign docker images

**What you expected to happen**
I expected all branches to end up with a signed image. 

**How to reproduce it (as minimally and precisely as possible)**
Run parallel Jenkins job with `vcn login` and `vcn notarize` shell commands 

**Additional info (any other context about the problem)**
Jenkins job runs inside dynamically created K8S pods and vcn itself runs inside a alpine based docker image.

**Comment by vchaindz** [comment]
Thanks for raising that topic. But that's a limitation by design in the free version.
You can simply circumvent it using a sleep.
That is also done here as an example:
https://github.com/codenotary/immudb/blob/master/.travis.yml

**Comment by jkornata** [comment]
Thank you for the clarification. In my opinion it would be a good idea to describe this in the docs. At least I couldn't find it.
